<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SocieteInfo extends \App\Entity\SocieteInfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'siren', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'ville_immatriculation', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'date_immatriculation', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'capital', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'forme_juridique', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'adresses'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'siren', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'ville_immatriculation', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'date_immatriculation', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'capital', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'forme_juridique', '' . "\0" . 'App\\Entity\\SocieteInfo' . "\0" . 'adresses'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SocieteInfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\SocieteInfo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiren(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiren', []);

        return parent::getSiren();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiren(int $siren): \App\Entity\SocieteInfo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiren', [$siren]);

        return parent::setSiren($siren);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleImmatriculation(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleImmatriculation', []);

        return parent::getVilleImmatriculation();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleImmatriculation(string $ville_immatriculation): \App\Entity\SocieteInfo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleImmatriculation', [$ville_immatriculation]);

        return parent::setVilleImmatriculation($ville_immatriculation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateImmatriculation(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateImmatriculation', []);

        return parent::getDateImmatriculation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateImmatriculation(int $date_immatriculation): \App\Entity\SocieteInfo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateImmatriculation', [$date_immatriculation]);

        return parent::setDateImmatriculation($date_immatriculation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapital(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapital', []);

        return parent::getCapital();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapital(int $capital): \App\Entity\SocieteInfo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapital', [$capital]);

        return parent::setCapital($capital);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormeJuridique(): \App\Entity\FormeJuridique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormeJuridique', []);

        return parent::getFormeJuridique();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormeJuridique(\App\Entity\FormeJuridique $forme_juridique): \App\Entity\SocieteInfo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormeJuridique', [$forme_juridique]);

        return parent::setFormeJuridique($forme_juridique);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresses(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresses', []);

        return parent::getAdresses();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressesSerialize(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressesSerialize', []);

        return parent::getAdressesSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdresse(\App\Entity\Adresse $adresse): \App\Entity\SocieteInfo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdresse', [$adresse]);

        return parent::addAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdresse(\App\Entity\Adresse $adresse): \App\Entity\SocieteInfo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdresse', [$adresse]);

        return parent::removeAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
