<?php

namespace ContainerKv53vR7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XXByjmTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XXByjmT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XXByjmT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FormeJuridiqueController::getFormesJuridiques' => ['privates', '.service_locator.toGAJ1P', 'get_ServiceLocator_ToGAJ1PService', true],
            'App\\Controller\\SocieteController::deleteAdresseSociete' => ['privates', '.service_locator.ayn_gIc', 'get_ServiceLocator_AynGIcService', true],
            'App\\Controller\\SocieteController::getSociete' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Controller\\SocieteController::postAdresseSociete' => ['privates', '.service_locator.ayn_gIc', 'get_ServiceLocator_AynGIcService', true],
            'App\\Controller\\SocieteController::postSocieteVersion' => ['privates', '.service_locator.M3GbiZF', 'get_ServiceLocator_M3GbiZFService', true],
            'App\\Controller\\SocieteController::putAdresseSociete' => ['privates', '.service_locator.ayn_gIc', 'get_ServiceLocator_AynGIcService', true],
            'App\\Controller\\SocieteController::putSociete' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Controller\\SocieteListController::deleteSociete' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Controller\\SocieteListController::getSocieteList' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Controller\\SocieteListController::postSociete' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\FormeJuridiqueController:getFormesJuridiques' => ['privates', '.service_locator.toGAJ1P', 'get_ServiceLocator_ToGAJ1PService', true],
            'App\\Controller\\SocieteController:deleteAdresseSociete' => ['privates', '.service_locator.ayn_gIc', 'get_ServiceLocator_AynGIcService', true],
            'App\\Controller\\SocieteController:getSociete' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Controller\\SocieteController:postAdresseSociete' => ['privates', '.service_locator.ayn_gIc', 'get_ServiceLocator_AynGIcService', true],
            'App\\Controller\\SocieteController:postSocieteVersion' => ['privates', '.service_locator.M3GbiZF', 'get_ServiceLocator_M3GbiZFService', true],
            'App\\Controller\\SocieteController:putAdresseSociete' => ['privates', '.service_locator.ayn_gIc', 'get_ServiceLocator_AynGIcService', true],
            'App\\Controller\\SocieteController:putSociete' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Controller\\SocieteListController:deleteSociete' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Controller\\SocieteListController:getSocieteList' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'App\\Controller\\SocieteListController:postSociete' => ['privates', '.service_locator.osSZ6zb', 'get_ServiceLocator_OsSZ6zbService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\FormeJuridiqueController::getFormesJuridiques' => '?',
            'App\\Controller\\SocieteController::deleteAdresseSociete' => '?',
            'App\\Controller\\SocieteController::getSociete' => '?',
            'App\\Controller\\SocieteController::postAdresseSociete' => '?',
            'App\\Controller\\SocieteController::postSocieteVersion' => '?',
            'App\\Controller\\SocieteController::putAdresseSociete' => '?',
            'App\\Controller\\SocieteController::putSociete' => '?',
            'App\\Controller\\SocieteListController::deleteSociete' => '?',
            'App\\Controller\\SocieteListController::getSocieteList' => '?',
            'App\\Controller\\SocieteListController::postSociete' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FormeJuridiqueController:getFormesJuridiques' => '?',
            'App\\Controller\\SocieteController:deleteAdresseSociete' => '?',
            'App\\Controller\\SocieteController:getSociete' => '?',
            'App\\Controller\\SocieteController:postAdresseSociete' => '?',
            'App\\Controller\\SocieteController:postSocieteVersion' => '?',
            'App\\Controller\\SocieteController:putAdresseSociete' => '?',
            'App\\Controller\\SocieteController:putSociete' => '?',
            'App\\Controller\\SocieteListController:deleteSociete' => '?',
            'App\\Controller\\SocieteListController:getSocieteList' => '?',
            'App\\Controller\\SocieteListController:postSociete' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
