<?php

namespace ContainerKv53vR7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdresseServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\AdresseService' shared autowired service.
     *
     * @return \App\Service\AdresseService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/AdresseService.php';

        $container->services['App\\Service\\AdresseService'] = $instance = new \App\Service\AdresseService(($container->privates['App\\Repository\\AdresseRepository'] ?? $container->load('getAdresseRepositoryService')), ($container->privates['App\\Repository\\SocieteInfoRepository'] ?? $container->load('getSocieteInfoRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Service\\AdresseService', $container));

        return $instance;
    }
}
