<?php

namespace ContainerKv53vR7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocieteServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\SocieteService' shared autowired service.
     *
     * @return \App\Service\SocieteService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SocieteService.php';

        $container->services['App\\Service\\SocieteService'] = $instance = new \App\Service\SocieteService(($container->privates['App\\Repository\\SocieteRepository'] ?? $container->load('getSocieteRepositoryService')), ($container->privates['App\\Repository\\FormeJuridiqueRepository'] ?? $container->load('getFormeJuridiqueRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Service\\SocieteService', $container));

        return $instance;
    }
}
