<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR2O1gJQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR2O1gJQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR2O1gJQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR2O1gJQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR2O1gJQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'R2O1gJQ',
    'container.build_id' => '2a382511',
    'container.build_time' => 1671140722,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR2O1gJQ');
