<?php

namespace ContainerR2O1gJQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OsSZ6zbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.osSZ6zb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.osSZ6zb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'societeService' => ['privates', 'App\\Service\\SocieteService', 'getSocieteServiceService', true],
        ], [
            'societeService' => 'App\\Service\\SocieteService',
        ]);
    }
}
