<?php

namespace ContainerR2O1gJQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ToGAJ1PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.toGAJ1P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.toGAJ1P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formeJuridiqueRepository' => ['privates', 'App\\Repository\\FormeJuridiqueRepository', 'getFormeJuridiqueRepositoryService', true],
        ], [
            'formeJuridiqueRepository' => 'App\\Repository\\FormeJuridiqueRepository',
        ]);
    }
}
