<?php

namespace ContainerR2O1gJQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdresseServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AdresseService' shared autowired service.
     *
     * @return \App\Service\AdresseService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AdresseService.php';

        return $container->privates['App\\Service\\AdresseService'] = new \App\Service\AdresseService(($container->privates['App\\Repository\\AdresseRepository'] ?? $container->load('getAdresseRepositoryService')), ($container->privates['App\\Repository\\SocieteInfoRepository'] ?? $container->load('getSocieteInfoRepositoryService')));
    }
}
