<?php

namespace ContainerR2O1gJQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocieteServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SocieteService' shared autowired service.
     *
     * @return \App\Service\SocieteService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SocieteService.php';

        return $container->privates['App\\Service\\SocieteService'] = new \App\Service\SocieteService(($container->privates['App\\Repository\\SocieteRepository'] ?? $container->load('getSocieteRepositoryService')), ($container->privates['App\\Repository\\FormeJuridiqueRepository'] ?? $container->load('getFormeJuridiqueRepositoryService')));
    }
}
