<?php

namespace ContainerR2O1gJQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocieteVersionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SocieteVersionService' shared autowired service.
     *
     * @return \App\Service\SocieteVersionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SocieteVersionService.php';

        return $container->privates['App\\Service\\SocieteVersionService'] = new \App\Service\SocieteVersionService(($container->privates['App\\Repository\\SocieteRepository'] ?? $container->load('getSocieteRepositoryService')), ($container->privates['App\\Repository\\SocieteVersionRepository'] ?? $container->load('getSocieteVersionRepositoryService')));
    }
}
